### ISSUE TITLE
How to troubleshoot an "invalid LEB128 sequence" exception?

### ISSUE THREAD

**Issue by dazza5000** [linkedin/dex-test-parser#25]
We are getting the following exception when running the DexParser via Flank:

```
Exception in thread "main" com.linkedin.dex.spec.DexException: invalid LEB128 sequence
	at com.linkedin.dex.spec.Leb128$Companion.readUnsignedLeb128(Leb128.kt:26)
	at com.linkedin.dex.parser.DecodedValue$Companion.create(DecodedValue.kt:56)
	at com.linkedin.dex.parser.AnnotationUtilsKt.getTestAnnotation(AnnotationUtils.kt:70)
	at com.linkedin.dex.parser.AnnotationUtilsKt.getClassAnnotationValues(AnnotationUtils.kt:46)
	at com.linkedin.dex.parser.TestMethodKt.createTestMethods(TestMethod.kt:42)
	at com.linkedin.dex.parser.JUnit4ExtensionsKt.findAllJUnit4Tests(JUnit4Extensions.kt:35)
	at com.linkedin.dex.parser.DexParser$Companion.findTestMethods(DexParser.kt:60)
	at com.linkedin.dex.parser.DexParser$Companion.findTestNames(DexParser.kt:45)
	at com.linkedin.dex.parser.DexParser$Companion.main(DexParser.kt:36)
	at com.linkedin.dex.parser.DexParser.main(DexParser.kt)
```

I put a screenshot of what the debugger looks like when the exception is thrown below. How would I go about debugging what the issue is. Thank you!

![screen shot 2018-10-31 at 5 40 18 pm](https://user-images.githubusercontent.com/1117489/47823079-9608d800-dd34-11e8-8546-1ac37ee9a7d8.png)

**Comment by dazza5000** [comment]
P.S. Thank you for the tool!

**Comment by hongbinh** [comment]
I'll provide some instructions before 11/21

**Comment by dazza5000** [comment]
no rush - we modified our project (we are using kotlin and java) and everything builds now - we think this had to do with the metadata that the kotlin compiler puts at the top of class files

**Comment by hongbinh** [comment]
@dazza5000, since you worked around it, we lowered the priority of this issue.

**Comment by drewhannay** [comment]
@dazza5000 do you have a way we can reproduce this issue? Otherwise it might make sense to just close this until we have more info

**Comment by dazza5000** [comment]
Sounds good. Apologies, but I found this on a large work project and I would not have permission to post the project here. Thank you for looking at it!
