### ISSUE TITLE
com.linkedin.dex.spec.DexException: Invalid dexMagic

### ISSUE THREAD

**Issue by bootstraponline** [linkedin/dex-test-parser#31]
SDK 28 is breaking dex test parser.

>  minSdkVersion 28

```
Caused by: com.linkedin.dex.spec.DexException: Invalid dexMagic:
DexMagic(dex=[100, 101, 120], newline=10, version=[48, 51, 57], zero=0)

	at com.linkedin.dex.spec.DexMagic.validate(DexMagic.kt:37)
	at com.linkedin.dex.spec.HeaderItem.validate(HeaderItem.kt:62)
	at com.linkedin.dex.spec.DexFile.<init>(DexFile.kt:35)
	at com.linkedin.dex.parser.DexParser$Companion$readDexFiles$1$4.invoke(DexParser.kt:73)
	at com.linkedin.dex.parser.DexParser$Companion$readDexFiles$1$4.invoke(DexParser.kt:23)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at com.linkedin.dex.parser.DexParser$Companion.readDexFiles(DexParser.kt:74)
	at com.linkedin.dex.parser.DexParser$Companion.findTestMethods(DexParser.kt:57)
	at ftl.args.AndroidArgs.getTestMethods(AndroidArgs.kt:113)
	at ftl.args.AndroidArgs.access$getTestMethods(AndroidArgs.kt:36)
	at ftl.args.AndroidArgs$testShardChunks$2.invoke(AndroidArgs.kt:87)
	at ftl.args.AndroidArgs$testShardChunks$2.invoke(AndroidArgs.kt:36)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ftl.args.AndroidArgs.getTestShardChunks(AndroidArgs.kt)
	at ftl.run.AndroidTestRunner$runTests$2.invokeSuspend(AndroidTestRunner.kt:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
	at kotlinx.coroutines.internal.ScopeCoroutine.onCompletionInternal$kotlinx_coroutines_core(Scopes.kt:28)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:305)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:230)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:34)
	at picocli.CommandLine.execute(CommandLine.java:1160)
	... 9 more
```

**Comment by hongbinh** [comment]
Seems your build has a new version number (0x39 / 57) even though it's not mentioned here yet: https://source.android.com/devices/tech/dalvik/dex-format#dex-file-magic
Adding 0x39 at this line should solve the problem:
https://github.com/linkedin/dex-test-parser/blob/8cde911a38de0ee969de704e5c6d53346a7fc885/parser/src/main/kotlin/com/linkedin/dex/spec/DexMagic.kt#L24

**Comment by hongbinh** [comment]
PR #32 is published for review

**Comment by hongbinh** [comment]
Fixed in https://github.com/linkedin/dex-test-parser/pull/32
