### ISSUE TITLE
invalid LEB128 sequence

### ISSUE THREAD

**Issue by carlospaulino** [linkedin/dex-test-parser#34]
For a while I’ve been trying to debug why I get `invalid LEB128 sequence` when working with some test apks. From what I can tell this occurs more often with binaries built with java 7 compatibility. It doesn't occur with binaries built with java 8 compatibility. 

I created a sample repo with two almost identical applications with the only difference being the compile compatibility.

```
invalid LEB128 sequence
com.linkedin.dex.spec.DexException: invalid LEB128 sequence
	at com.linkedin.dex.spec.Leb128$Companion.readUnsignedLeb128(Leb128.kt:26)
	at com.linkedin.dex.parser.DecodedValue$Companion.create(DecodedValue.kt:56)
	at com.linkedin.dex.parser.AnnotationUtilsKt.getTestAnnotation(AnnotationUtils.kt:70)
	at com.linkedin.dex.parser.AnnotationUtilsKt.getClassAnnotationValues(AnnotationUtils.kt:46)
	at com.linkedin.dex.parser.TestMethodKt.createTestMethods(TestMethod.kt:42)
	at com.linkedin.dex.parser.JUnit4ExtensionsKt.findAllJUnit4Tests(JUnit4Extensions.kt:35)
	at com.linkedin.dex.parser.DexParser$Companion.findTestMethods(DexParser.kt:60)
```

Repo is available here: 
https://github.com/carlospaulino/dex-test-parser-bug

**Comment by hongbinh** [comment]
@kkoser found the actual problem is in DecodedValue.kt:54 , we will send a PR with some added tests soon.

**Comment by hongbinh** [comment]
I think I'll add a readUnsignedLeb128Long(byteBuffer: ByteBuffer) to return long as the fix

**Comment by carlospaulino** [comment]
@hongbinh @kkoser Thanks a lot. I am looking forward to the next release.
